### ISSUE TITLE
Issue when executing workflow "Update Wiki"

### ISSUE THREAD

**Issue by OlgaCalderon** [sngular/openapi-nodejs-cli#56]
@jorgecasar has detected an issue when executing the workflow "update-wiki.yml". 

The failed job is: https://github.com/sngular/openapi-nodejs-cli/actions/runs/5268895028/jobs/9526245890

![image](https://github.com/sngular/openapi-nodejs-cli/assets/127837946/a2cff202-4afc-4895-9c3a-24c77d3ecd31)

The same workflow works in other repositories, as [kloadgen](https://github.com/sngular/kloadgen/blob/master/.github/workflows/update-wiki.yml#L31), not expecting a user for the `git clone` command.

It is necessary to research a solution for this issue.

**Comment by adantoscano** [comment]
The problem is that wiki wasn't exists and that clone received a 404. I opened the wiki so now should work.

Thanks!🤗
