### ISSUE TITLE
Cache downloads

### ISSUE THREAD

**Issue by halvardssm** [sngular/openapi-nodejs-cli#64]
Hi! I want to use this package in a pipeline, and I see that it is downloading the binary in the beginning. Is there a way to set download location using an env variable, in the hopes of caching the binary?

**Comment by jorgecasar** [comment]
Hi @halvardssm 

Do you mean npm cache? By default it cache inside `${HOME}/.npm` maybe you can't cache this directory in your pipeline like occurs in Gitlab. Then, you use run `--cache` to change the cache folder destination were you want. I recommend to set it in `.npm` inside your current folder using `npm ci --cache .npm`. And include this folder into the pipeline cache

**Comment by halvardssm** [comment]
Hi @jorgecasar! I am unsure to be honest, when running the script, I am seeing this when successful:

<img width="265" alt="Screenshot 2023-09-15 at 10 02 32" src="https://github.com/sngular/openapi-nodejs-cli/assets/33620089/1c45bca8-2ff0-4bbb-85c3-cd0a738cfc26">

And occasionally this when unsuccessful:

<img width="610" alt="Screenshot 2023-09-15 at 10 03 00" src="https://github.com/sngular/openapi-nodejs-cli/assets/33620089/f222570b-6f69-4dd4-9b7a-660869136a05">

I am assuming this is because the server that it needs to be downloaded from is overloaded, so I was hoping to cache this somewhere. The problem is that I can't find the download path for this download so that I can cache it.

**Comment by jorgecasar** [comment]
Then I'm not sure what are you talking about. This is a command line to generate code and then you can complete and deploy where you want.

Are you talking about generating process or the resulting server?

**Comment by halvardssm** [comment]
I am very sorry, I realized I was in the wrong repository (issue is related to [this](https://github.com/OpenAPITools/openapi-generator-cli) repo). Thank you for your help!
